version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8082"
      - "--providers.file.directory=/configuration"
      - "--providers.file.watch=true"
    ports:
      - "8082:8082"
      - "8080:8080"
    networks:
      - backend
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/ben/traefik/configuration/:/configuration/"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  fast:
    image: fast:latest
    build: ./app/
    #container_name: "fast"
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fast.rule=Host(`adamant.tator.io`)"
      - "traefik.http.routers.fast.entrypoints=web"
      - "traefik.http.routers.fast.tls=true"
      - "traefik.http.middlewares.addHeader.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT"
      - "traefik.http.middlewares.addHeader.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.addHeader.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.addHeader.headers.addvaryheader=true"
      - "traefik.http.routers.fast.middlewares=addHeader"
    volumes:
      - ./app:/app/app
      - ./images:/images
      - ./script:/script
      - ./static-files:/static-files
    entrypoint: /start-reload.sh

networks:
  traefik-public:
    external: true
  backend:
    external: false