version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:${SERVER_PORT}"
      - "--providers.file.directory=/configuration"
      - "--providers.file.watch=true"
    ports:
      - "8092:8092"
      - "8093:8080"
    networks:
      - backend
      - traefik-public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${TRAEFIK_CONFIG}:/configuration/"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  fast:
    image: fast:latest
    build: ./app/
    #container_name: "fast"
    environment:
      SERVER_URL : "${SERVER_URL}"
      SERVER_PORT : "${SERVER_PORT}"
    networks:
      - backend
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fast.rule=Host(`${SERVER_HOST}`)"
      - "traefik.http.routers.fast.entrypoints=web"
      - "traefik.http.routers.fast.tls=true"
    volumes:
      - ./app:/app/app
      - ./script:/script
      - ./static-files:/static-files
    entrypoint: /start-reload.sh

networks:
  traefik-public:
    external: true
  backend:
    external: false
